// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Servo.Sharp
{
    internal static unsafe partial class ServoNative
    {
        const string __DllName = "servo_ffi";





        [DllImport(__DllName, EntryPoint = "servo_last_error", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* servo_last_error();

        [DllImport(__DllName, EntryPoint = "servo_free_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void servo_free_string(byte* ptr);

        [DllImport(__DllName, EntryPoint = "servo_free_bytes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void servo_free_bytes(byte* ptr, nuint len);

        [DllImport(__DllName, EntryPoint = "servo_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* servo_new(CEventLoopWaker waker, byte* resource_path);

        [DllImport(__DllName, EntryPoint = "servo_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void servo_destroy(void* handle);

        [DllImport(__DllName, EntryPoint = "servo_spin_event_loop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void servo_spin_event_loop(void* handle);

        [DllImport(__DllName, EntryPoint = "servo_set_delegate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void servo_set_delegate(void* handle, ServoCallbacks callbacks);

        [DllImport(__DllName, EntryPoint = "servo_set_preference", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void servo_set_preference(void* handle, byte* name, byte* value);

        [DllImport(__DllName, EntryPoint = "rendering_context_new_software", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* rendering_context_new_software(uint width, uint height);

        [DllImport(__DllName, EntryPoint = "rendering_context_new_hardware", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* rendering_context_new_hardware(uint width, uint height);

        [DllImport(__DllName, EntryPoint = "rendering_context_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rendering_context_destroy(void* handle);

        [DllImport(__DllName, EntryPoint = "rendering_context_resize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rendering_context_resize(void* handle, uint width, uint height);

        [DllImport(__DllName, EntryPoint = "rendering_context_present", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rendering_context_present(void* handle);

        [DllImport(__DllName, EntryPoint = "rendering_context_make_current", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte rendering_context_make_current(void* handle);

        [DllImport(__DllName, EntryPoint = "rendering_context_read_pixels", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* rendering_context_read_pixels(void* handle, uint* out_width, uint* out_height, nuint* out_len);

        [DllImport(__DllName, EntryPoint = "rendering_context_read_pixels_into", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte rendering_context_read_pixels_into(void* handle, byte* dest, nuint dest_len, uint* out_width, uint* out_height);

        [DllImport(__DllName, EntryPoint = "webview_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* webview_new(void* servo_handle, void* rendering_ctx_handle, WebViewCallbacks callbacks, ClipboardCallbacks clipboard, byte* initial_url);

        [DllImport(__DllName, EntryPoint = "webview_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_destroy(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_load_url", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_load_url(void* handle, byte* url);

        [DllImport(__DllName, EntryPoint = "webview_reload", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_reload(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_go_back", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_go_back(void* handle, nuint steps);

        [DllImport(__DllName, EntryPoint = "webview_go_forward", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_go_forward(void* handle, nuint steps);

        [DllImport(__DllName, EntryPoint = "webview_paint", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_paint(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_resize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_resize(void* handle, uint width, uint height);

        [DllImport(__DllName, EntryPoint = "webview_focus", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_focus(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_blur", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_blur(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_show", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_show(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_hide", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_hide(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_set_hidpi_scale", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_set_hidpi_scale(void* handle, float scale);

        [DllImport(__DllName, EntryPoint = "webview_get_url", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* webview_get_url(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_get_title", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* webview_get_title(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_get_load_status", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte webview_get_load_status(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_get_cursor", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte webview_get_cursor(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_is_focused", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte webview_is_focused(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_is_animating", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte webview_is_animating(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_can_go_back", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte webview_can_go_back(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_can_go_forward", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte webview_can_go_forward(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_send_mouse_button", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong webview_send_mouse_button(void* handle, byte action, ushort button, float x, float y);

        [DllImport(__DllName, EntryPoint = "webview_send_mouse_move", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong webview_send_mouse_move(void* handle, float x, float y);

        [DllImport(__DllName, EntryPoint = "webview_send_mouse_left_viewport", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong webview_send_mouse_left_viewport(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_send_key_event", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong webview_send_key_event(void* handle, byte state, uint key_char, byte* key_code, uint modifiers);

        [DllImport(__DllName, EntryPoint = "webview_send_wheel", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong webview_send_wheel(void* handle, double delta_x, double delta_y, double delta_z, byte mode, float x, float y);

        [DllImport(__DllName, EntryPoint = "webview_send_scroll", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_send_scroll(void* handle, float delta_x, float delta_y, float point_x, float point_y);

        [DllImport(__DllName, EntryPoint = "webview_send_touch", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong webview_send_touch(void* handle, byte event_type, int touch_id, float x, float y);

        [DllImport(__DllName, EntryPoint = "webview_send_editing_action", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong webview_send_editing_action(void* handle, byte action);

        [DllImport(__DllName, EntryPoint = "webview_set_page_zoom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_set_page_zoom(void* handle, float zoom);

        [DllImport(__DllName, EntryPoint = "webview_get_page_zoom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern float webview_get_page_zoom(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_exit_fullscreen", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_exit_fullscreen(void* handle);

        [DllImport(__DllName, EntryPoint = "webview_set_throttled", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_set_throttled(void* handle, byte throttled);

        [DllImport(__DllName, EntryPoint = "webview_evaluate_javascript", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_evaluate_javascript(void* handle, byte* script, delegate* unmanaged[Cdecl]<void*, byte*, byte*, void> callback, void* callback_data);

        [DllImport(__DllName, EntryPoint = "dialog_alert_dismiss", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void dialog_alert_dismiss(nuint dialog_handle);

        [DllImport(__DllName, EntryPoint = "dialog_confirm_respond", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void dialog_confirm_respond(nuint dialog_handle, byte confirmed);

        [DllImport(__DllName, EntryPoint = "dialog_prompt_respond", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void dialog_prompt_respond(nuint dialog_handle, byte* value);

        [DllImport(__DllName, EntryPoint = "navigation_request_allow", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void navigation_request_allow(nuint request_handle);

        [DllImport(__DllName, EntryPoint = "navigation_request_deny", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void navigation_request_deny(nuint request_handle);

        [DllImport(__DllName, EntryPoint = "permission_request_allow", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void permission_request_allow(nuint request_handle);

        [DllImport(__DllName, EntryPoint = "permission_request_deny", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void permission_request_deny(nuint request_handle);

        [DllImport(__DllName, EntryPoint = "unload_request_allow", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void unload_request_allow(nuint request_handle);

        [DllImport(__DllName, EntryPoint = "unload_request_deny", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void unload_request_deny(nuint request_handle);

        [DllImport(__DllName, EntryPoint = "select_element_respond", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void select_element_respond(nuint request_handle, long selected_id);

        [DllImport(__DllName, EntryPoint = "webview_take_screenshot", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void webview_take_screenshot(void* handle, delegate* unmanaged[Cdecl]<void*, byte*, uint, uint, nuint, void> callback, void* callback_data);

        [DllImport(__DllName, EntryPoint = "webview_get_favicon", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* webview_get_favicon(void* handle, uint* out_width, uint* out_height, byte* out_format, nuint* out_len);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CEventLoopWaker
    {
        public void* user_data;
        public delegate* unmanaged[Cdecl]<void*, void> wake;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ServoCallbacks
    {
        public void* user_data;
        public delegate* unmanaged[Cdecl]<void*, byte, byte*, void> on_error;
        public delegate* unmanaged[Cdecl]<void*, ushort, byte*, void> on_devtools_started;
        public delegate* unmanaged[Cdecl]<void*, byte, byte*, void> on_console_message;
        public delegate* unmanaged[Cdecl]<void*, byte> on_request_devtools_connection;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct WebViewCallbacks
    {
        public void* user_data;
        public delegate* unmanaged[Cdecl]<void*, void> on_new_frame_ready;
        public delegate* unmanaged[Cdecl]<void*, byte, void> on_load_status_changed;
        public delegate* unmanaged[Cdecl]<void*, byte*, void> on_url_changed;
        public delegate* unmanaged[Cdecl]<void*, byte*, void> on_title_changed;
        public delegate* unmanaged[Cdecl]<void*, byte, void> on_cursor_changed;
        public delegate* unmanaged[Cdecl]<void*, byte, void> on_focus_changed;
        public delegate* unmanaged[Cdecl]<void*, byte, void> on_animating_changed;
        public delegate* unmanaged[Cdecl]<void*, void> on_favicon_changed;
        public delegate* unmanaged[Cdecl]<void*, ulong, byte, void> on_input_event_handled;
        public delegate* unmanaged[Cdecl]<void*, nuint, nuint, void> on_history_changed;
        public delegate* unmanaged[Cdecl]<void*, void> on_closed;
        public delegate* unmanaged[Cdecl]<void*, byte, void> on_fullscreen_changed;
        public delegate* unmanaged[Cdecl]<void*, byte*, byte*, void> on_crashed;
        public delegate* unmanaged[Cdecl]<void*, byte, byte*, void> on_console_message;
        public delegate* unmanaged[Cdecl]<void*, byte*, nuint, void> on_show_alert;
        public delegate* unmanaged[Cdecl]<void*, byte*, nuint, void> on_show_confirm;
        public delegate* unmanaged[Cdecl]<void*, byte*, byte*, nuint, void> on_show_prompt;
        public delegate* unmanaged[Cdecl]<void*, byte*, nuint, void> on_request_navigation;
        public delegate* unmanaged[Cdecl]<void*, byte, nuint, void> on_request_permission;
        public delegate* unmanaged[Cdecl]<void*, nuint, void> on_request_unload;
        public delegate* unmanaged[Cdecl]<void*, byte, byte*, void> on_media_session_event;
        public delegate* unmanaged[Cdecl]<void*, byte*, long, int, int, int, int, nuint, void> on_show_select_element;
        public delegate* unmanaged[Cdecl]<void*, CScreenGeometry*, byte> get_screen_geometry;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ClipboardCallbacks
    {
        public void* user_data;
        public delegate* unmanaged[Cdecl]<void*, byte*> get_text;
        public delegate* unmanaged[Cdecl]<void*, byte*, void> set_text;
        public delegate* unmanaged[Cdecl]<void*, void> clear;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CScreenGeometry
    {
        public int size_width;
        public int size_height;
        public int available_width;
        public int available_height;
        public int window_x;
        public int window_y;
        public int window_width;
        public int window_height;
    }



}
